//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int Customer_Id { get; set; }
        public int Type_Number { get; set; }
        public int From_Account_Id { get; set; }
        public Nullable<int> To_Account_Id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Transaction_Type Transaction_Type { get; set; }
    }
}
