//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://schemas.datacontract.org/2004/07/BankService.Models")]
    [System.SerializableAttribute()]
    public partial class Bank : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Routing_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Routing_Number {
            get {
                return this.Routing_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Routing_NumberField, value) != true)) {
                    this.Routing_NumberField = value;
                    this.RaisePropertyChanged("Routing_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/BankService.Models")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Bank_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Customer_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Interest_RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Type_NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bank_Id {
            get {
                return this.Bank_IdField;
            }
            set {
                if ((this.Bank_IdField.Equals(value) != true)) {
                    this.Bank_IdField = value;
                    this.RaisePropertyChanged("Bank_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Customer_Id {
            get {
                return this.Customer_IdField;
            }
            set {
                if ((this.Customer_IdField.Equals(value) != true)) {
                    this.Customer_IdField = value;
                    this.RaisePropertyChanged("Customer_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Interest_Rate {
            get {
                return this.Interest_RateField;
            }
            set {
                if ((this.Interest_RateField.Equals(value) != true)) {
                    this.Interest_RateField = value;
                    this.RaisePropertyChanged("Interest_Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type_Number {
            get {
                return this.Type_NumberField;
            }
            set {
                if ((this.Type_NumberField.Equals(value) != true)) {
                    this.Type_NumberField = value;
                    this.RaisePropertyChanged("Type_Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account_Type", Namespace="http://schemas.datacontract.org/2004/07/BankService.Models")]
    [System.SerializableAttribute()]
    public partial class Account_Type : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/BankService.Models")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Bank_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Middle_InitialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bank_Id {
            get {
                return this.Bank_IdField;
            }
            set {
                if ((this.Bank_IdField.Equals(value) != true)) {
                    this.Bank_IdField = value;
                    this.RaisePropertyChanged("Bank_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Middle_Initial {
            get {
                return this.Middle_InitialField;
            }
            set {
                if ((object.ReferenceEquals(this.Middle_InitialField, value) != true)) {
                    this.Middle_InitialField = value;
                    this.RaisePropertyChanged("Middle_Initial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/BankService.Models")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Bank_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Middle_InitialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bank_Id {
            get {
                return this.Bank_IdField;
            }
            set {
                if ((this.Bank_IdField.Equals(value) != true)) {
                    this.Bank_IdField = value;
                    this.RaisePropertyChanged("Bank_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Middle_Initial {
            get {
                return this.Middle_InitialField;
            }
            set {
                if ((object.ReferenceEquals(this.Middle_InitialField, value) != true)) {
                    this.Middle_InitialField = value;
                    this.RaisePropertyChanged("Middle_Initial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/BankService.Models")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Customer_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> From_Account_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> To_Account_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Type_NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Customer_Id {
            get {
                return this.Customer_IdField;
            }
            set {
                if ((this.Customer_IdField.Equals(value) != true)) {
                    this.Customer_IdField = value;
                    this.RaisePropertyChanged("Customer_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> From_Account_Id {
            get {
                return this.From_Account_IdField;
            }
            set {
                if ((this.From_Account_IdField.Equals(value) != true)) {
                    this.From_Account_IdField = value;
                    this.RaisePropertyChanged("From_Account_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> To_Account_Id {
            get {
                return this.To_Account_IdField;
            }
            set {
                if ((this.To_Account_IdField.Equals(value) != true)) {
                    this.To_Account_IdField = value;
                    this.RaisePropertyChanged("To_Account_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type_Number {
            get {
                return this.Type_NumberField;
            }
            set {
                if ((this.Type_NumberField.Equals(value) != true)) {
                    this.Type_NumberField = value;
                    this.RaisePropertyChanged("Type_Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction_Type", Namespace="http://schemas.datacontract.org/2004/07/BankService.Models")]
    [System.SerializableAttribute()]
    public partial class Transaction_Type : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllBanks", ReplyAction="http://tempuri.org/IDataService/GetAllBanksResponse")]
        System.Collections.Generic.List<UI.DataService.Bank> GetAllBanks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllBanks", ReplyAction="http://tempuri.org/IDataService/GetAllBanksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Bank>> GetAllBanksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetBank", ReplyAction="http://tempuri.org/IDataService/GetBankResponse")]
        UI.DataService.Bank GetBank(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetBank", ReplyAction="http://tempuri.org/IDataService/GetBankResponse")]
        System.Threading.Tasks.Task<UI.DataService.Bank> GetBankAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAccount", ReplyAction="http://tempuri.org/IDataService/GetAccountResponse")]
        UI.DataService.Account GetAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAccount", ReplyAction="http://tempuri.org/IDataService/GetAccountResponse")]
        System.Threading.Tasks.Task<UI.DataService.Account> GetAccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAccountType", ReplyAction="http://tempuri.org/IDataService/GetAccountTypeResponse")]
        UI.DataService.Account_Type GetAccountType(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAccountType", ReplyAction="http://tempuri.org/IDataService/GetAccountTypeResponse")]
        System.Threading.Tasks.Task<UI.DataService.Account_Type> GetAccountTypeAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCustomer", ReplyAction="http://tempuri.org/IDataService/GetCustomerResponse")]
        UI.DataService.Customer GetCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCustomer", ReplyAction="http://tempuri.org/IDataService/GetCustomerResponse")]
        System.Threading.Tasks.Task<UI.DataService.Customer> GetCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetEmployee", ReplyAction="http://tempuri.org/IDataService/GetEmployeeResponse")]
        UI.DataService.Employee GetEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetEmployee", ReplyAction="http://tempuri.org/IDataService/GetEmployeeResponse")]
        System.Threading.Tasks.Task<UI.DataService.Employee> GetEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTransaction", ReplyAction="http://tempuri.org/IDataService/GetTransactionResponse")]
        UI.DataService.Transaction GetTransaction(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTransaction", ReplyAction="http://tempuri.org/IDataService/GetTransactionResponse")]
        System.Threading.Tasks.Task<UI.DataService.Transaction> GetTransactionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTransactionType", ReplyAction="http://tempuri.org/IDataService/GetTransactionTypeResponse")]
        UI.DataService.Transaction_Type GetTransactionType(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTransactionType", ReplyAction="http://tempuri.org/IDataService/GetTransactionTypeResponse")]
        System.Threading.Tasks.Task<UI.DataService.Transaction_Type> GetTransactionTypeAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllAccounts", ReplyAction="http://tempuri.org/IDataService/GetAllAccountsResponse")]
        System.Collections.Generic.List<UI.DataService.Account> GetAllAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllAccounts", ReplyAction="http://tempuri.org/IDataService/GetAllAccountsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Account>> GetAllAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllAccountTypes", ReplyAction="http://tempuri.org/IDataService/GetAllAccountTypesResponse")]
        System.Collections.Generic.List<UI.DataService.Account_Type> GetAllAccountTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllAccountTypes", ReplyAction="http://tempuri.org/IDataService/GetAllAccountTypesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Account_Type>> GetAllAccountTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllCustomers", ReplyAction="http://tempuri.org/IDataService/GetAllCustomersResponse")]
        System.Collections.Generic.List<UI.DataService.Customer> GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllCustomers", ReplyAction="http://tempuri.org/IDataService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Customer>> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllEmployees", ReplyAction="http://tempuri.org/IDataService/GetAllEmployeesResponse")]
        System.Collections.Generic.List<UI.DataService.Employee> GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllEmployees", ReplyAction="http://tempuri.org/IDataService/GetAllEmployeesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Employee>> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllTransactions", ReplyAction="http://tempuri.org/IDataService/GetAllTransactionsResponse")]
        System.Collections.Generic.List<UI.DataService.Transaction> GetAllTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllTransactions", ReplyAction="http://tempuri.org/IDataService/GetAllTransactionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Transaction>> GetAllTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllTransactionTypes", ReplyAction="http://tempuri.org/IDataService/GetAllTransactionTypesResponse")]
        System.Collections.Generic.List<UI.DataService.Transaction_Type> GetAllTransactionTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllTransactionTypes", ReplyAction="http://tempuri.org/IDataService/GetAllTransactionTypesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Transaction_Type>> GetAllTransactionTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Bank", ReplyAction="http://tempuri.org/IDataService/Add_BankResponse")]
        void Add_Bank(UI.DataService.Bank bank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Bank", ReplyAction="http://tempuri.org/IDataService/Add_BankResponse")]
        System.Threading.Tasks.Task Add_BankAsync(UI.DataService.Bank bank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Bank", ReplyAction="http://tempuri.org/IDataService/Remove_BankResponse")]
        void Remove_Bank(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Bank", ReplyAction="http://tempuri.org/IDataService/Remove_BankResponse")]
        System.Threading.Tasks.Task Remove_BankAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Bank", ReplyAction="http://tempuri.org/IDataService/Update_BankResponse")]
        void Update_Bank(UI.DataService.Bank bank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Bank", ReplyAction="http://tempuri.org/IDataService/Update_BankResponse")]
        System.Threading.Tasks.Task Update_BankAsync(UI.DataService.Bank bank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Account", ReplyAction="http://tempuri.org/IDataService/Add_AccountResponse")]
        void Add_Account(UI.DataService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Account", ReplyAction="http://tempuri.org/IDataService/Add_AccountResponse")]
        System.Threading.Tasks.Task Add_AccountAsync(UI.DataService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Account", ReplyAction="http://tempuri.org/IDataService/Remove_AccountResponse")]
        void Remove_Account(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Account", ReplyAction="http://tempuri.org/IDataService/Remove_AccountResponse")]
        System.Threading.Tasks.Task Remove_AccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Account", ReplyAction="http://tempuri.org/IDataService/Update_AccountResponse")]
        void Update_Account(UI.DataService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Account", ReplyAction="http://tempuri.org/IDataService/Update_AccountResponse")]
        System.Threading.Tasks.Task Update_AccountAsync(UI.DataService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Account_Type", ReplyAction="http://tempuri.org/IDataService/Add_Account_TypeResponse")]
        void Add_Account_Type(UI.DataService.Account_Type accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Account_Type", ReplyAction="http://tempuri.org/IDataService/Add_Account_TypeResponse")]
        System.Threading.Tasks.Task Add_Account_TypeAsync(UI.DataService.Account_Type accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Account_Type", ReplyAction="http://tempuri.org/IDataService/Remove_Account_TypeResponse")]
        void Remove_Account_Type(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Account_Type", ReplyAction="http://tempuri.org/IDataService/Remove_Account_TypeResponse")]
        System.Threading.Tasks.Task Remove_Account_TypeAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Account_Type", ReplyAction="http://tempuri.org/IDataService/Update_Account_TypeResponse")]
        void Update_Account_Type(UI.DataService.Account_Type accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Account_Type", ReplyAction="http://tempuri.org/IDataService/Update_Account_TypeResponse")]
        System.Threading.Tasks.Task Update_Account_TypeAsync(UI.DataService.Account_Type accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Customer", ReplyAction="http://tempuri.org/IDataService/Add_CustomerResponse")]
        void Add_Customer(UI.DataService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Customer", ReplyAction="http://tempuri.org/IDataService/Add_CustomerResponse")]
        System.Threading.Tasks.Task Add_CustomerAsync(UI.DataService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Customer", ReplyAction="http://tempuri.org/IDataService/Remove_CustomerResponse")]
        void Remove_Customer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Customer", ReplyAction="http://tempuri.org/IDataService/Remove_CustomerResponse")]
        System.Threading.Tasks.Task Remove_CustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Customer", ReplyAction="http://tempuri.org/IDataService/Update_CustomerResponse")]
        void Update_Customer(UI.DataService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Customer", ReplyAction="http://tempuri.org/IDataService/Update_CustomerResponse")]
        System.Threading.Tasks.Task Update_CustomerAsync(UI.DataService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Employee", ReplyAction="http://tempuri.org/IDataService/Add_EmployeeResponse")]
        void Add_Employee(UI.DataService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Employee", ReplyAction="http://tempuri.org/IDataService/Add_EmployeeResponse")]
        System.Threading.Tasks.Task Add_EmployeeAsync(UI.DataService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Employee", ReplyAction="http://tempuri.org/IDataService/Remove_EmployeeResponse")]
        void Remove_Employee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Employee", ReplyAction="http://tempuri.org/IDataService/Remove_EmployeeResponse")]
        System.Threading.Tasks.Task Remove_EmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Employee", ReplyAction="http://tempuri.org/IDataService/Update_EmployeeResponse")]
        void Update_Employee(UI.DataService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Employee", ReplyAction="http://tempuri.org/IDataService/Update_EmployeeResponse")]
        System.Threading.Tasks.Task Update_EmployeeAsync(UI.DataService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Transaction", ReplyAction="http://tempuri.org/IDataService/Add_TransactionResponse")]
        void Add_Transaction(UI.DataService.Transaction transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Transaction", ReplyAction="http://tempuri.org/IDataService/Add_TransactionResponse")]
        System.Threading.Tasks.Task Add_TransactionAsync(UI.DataService.Transaction transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Transaction", ReplyAction="http://tempuri.org/IDataService/Remove_TransactionResponse")]
        void Remove_Transaction(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Transaction", ReplyAction="http://tempuri.org/IDataService/Remove_TransactionResponse")]
        System.Threading.Tasks.Task Remove_TransactionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Transaction", ReplyAction="http://tempuri.org/IDataService/Update_TransactionResponse")]
        void Update_Transaction(UI.DataService.Transaction transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Transaction", ReplyAction="http://tempuri.org/IDataService/Update_TransactionResponse")]
        System.Threading.Tasks.Task Update_TransactionAsync(UI.DataService.Transaction transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Transaction_Type", ReplyAction="http://tempuri.org/IDataService/Add_Transaction_TypeResponse")]
        void Add_Transaction_Type(UI.DataService.Transaction_Type transactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Add_Transaction_Type", ReplyAction="http://tempuri.org/IDataService/Add_Transaction_TypeResponse")]
        System.Threading.Tasks.Task Add_Transaction_TypeAsync(UI.DataService.Transaction_Type transactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Transaction_Type", ReplyAction="http://tempuri.org/IDataService/Remove_Transaction_TypeResponse")]
        void Remove_Transaction_Type(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Remove_Transaction_Type", ReplyAction="http://tempuri.org/IDataService/Remove_Transaction_TypeResponse")]
        System.Threading.Tasks.Task Remove_Transaction_TypeAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Transaction_Type", ReplyAction="http://tempuri.org/IDataService/Update_Transaction_TypeResponse")]
        void Update_Transaction_Type(UI.DataService.Transaction_Type transactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Update_Transaction_Type", ReplyAction="http://tempuri.org/IDataService/Update_Transaction_TypeResponse")]
        System.Threading.Tasks.Task Update_Transaction_TypeAsync(UI.DataService.Transaction_Type transactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCustomersofBank", ReplyAction="http://tempuri.org/IDataService/GetCustomersofBankResponse")]
        System.Collections.Generic.List<UI.DataService.Customer> GetCustomersofBank(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCustomersofBank", ReplyAction="http://tempuri.org/IDataService/GetCustomersofBankResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Customer>> GetCustomersofBankAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetEmployeesofBank", ReplyAction="http://tempuri.org/IDataService/GetEmployeesofBankResponse")]
        System.Collections.Generic.List<UI.DataService.Employee> GetEmployeesofBank(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetEmployeesofBank", ReplyAction="http://tempuri.org/IDataService/GetEmployeesofBankResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Employee>> GetEmployeesofBankAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAccountsofCustomer", ReplyAction="http://tempuri.org/IDataService/GetAccountsofCustomerResponse")]
        System.Collections.Generic.List<UI.DataService.Account> GetAccountsofCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAccountsofCustomer", ReplyAction="http://tempuri.org/IDataService/GetAccountsofCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Account>> GetAccountsofCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTransactionsofCustomer", ReplyAction="http://tempuri.org/IDataService/GetTransactionsofCustomerResponse")]
        System.Collections.Generic.List<UI.DataService.Transaction> GetTransactionsofCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTransactionsofCustomer", ReplyAction="http://tempuri.org/IDataService/GetTransactionsofCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Transaction>> GetTransactionsofCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/MakeTransaction", ReplyAction="http://tempuri.org/IDataService/MakeTransactionResponse")]
        void MakeTransaction(UI.DataService.Transaction transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/MakeTransaction", ReplyAction="http://tempuri.org/IDataService/MakeTransactionResponse")]
        System.Threading.Tasks.Task MakeTransactionAsync(UI.DataService.Transaction transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/MakeSome", ReplyAction="http://tempuri.org/IDataService/MakeSomeResponse")]
        void MakeSome();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/MakeSome", ReplyAction="http://tempuri.org/IDataService/MakeSomeResponse")]
        System.Threading.Tasks.Task MakeSomeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : UI.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<UI.DataService.IDataService>, UI.DataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<UI.DataService.Bank> GetAllBanks() {
            return base.Channel.GetAllBanks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Bank>> GetAllBanksAsync() {
            return base.Channel.GetAllBanksAsync();
        }
        
        public UI.DataService.Bank GetBank(int id) {
            return base.Channel.GetBank(id);
        }
        
        public System.Threading.Tasks.Task<UI.DataService.Bank> GetBankAsync(int id) {
            return base.Channel.GetBankAsync(id);
        }
        
        public UI.DataService.Account GetAccount(int id) {
            return base.Channel.GetAccount(id);
        }
        
        public System.Threading.Tasks.Task<UI.DataService.Account> GetAccountAsync(int id) {
            return base.Channel.GetAccountAsync(id);
        }
        
        public UI.DataService.Account_Type GetAccountType(int number) {
            return base.Channel.GetAccountType(number);
        }
        
        public System.Threading.Tasks.Task<UI.DataService.Account_Type> GetAccountTypeAsync(int number) {
            return base.Channel.GetAccountTypeAsync(number);
        }
        
        public UI.DataService.Customer GetCustomer(int id) {
            return base.Channel.GetCustomer(id);
        }
        
        public System.Threading.Tasks.Task<UI.DataService.Customer> GetCustomerAsync(int id) {
            return base.Channel.GetCustomerAsync(id);
        }
        
        public UI.DataService.Employee GetEmployee(int id) {
            return base.Channel.GetEmployee(id);
        }
        
        public System.Threading.Tasks.Task<UI.DataService.Employee> GetEmployeeAsync(int id) {
            return base.Channel.GetEmployeeAsync(id);
        }
        
        public UI.DataService.Transaction GetTransaction(int id) {
            return base.Channel.GetTransaction(id);
        }
        
        public System.Threading.Tasks.Task<UI.DataService.Transaction> GetTransactionAsync(int id) {
            return base.Channel.GetTransactionAsync(id);
        }
        
        public UI.DataService.Transaction_Type GetTransactionType(int number) {
            return base.Channel.GetTransactionType(number);
        }
        
        public System.Threading.Tasks.Task<UI.DataService.Transaction_Type> GetTransactionTypeAsync(int number) {
            return base.Channel.GetTransactionTypeAsync(number);
        }
        
        public System.Collections.Generic.List<UI.DataService.Account> GetAllAccounts() {
            return base.Channel.GetAllAccounts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Account>> GetAllAccountsAsync() {
            return base.Channel.GetAllAccountsAsync();
        }
        
        public System.Collections.Generic.List<UI.DataService.Account_Type> GetAllAccountTypes() {
            return base.Channel.GetAllAccountTypes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Account_Type>> GetAllAccountTypesAsync() {
            return base.Channel.GetAllAccountTypesAsync();
        }
        
        public System.Collections.Generic.List<UI.DataService.Customer> GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Customer>> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public System.Collections.Generic.List<UI.DataService.Employee> GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Employee>> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public System.Collections.Generic.List<UI.DataService.Transaction> GetAllTransactions() {
            return base.Channel.GetAllTransactions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Transaction>> GetAllTransactionsAsync() {
            return base.Channel.GetAllTransactionsAsync();
        }
        
        public System.Collections.Generic.List<UI.DataService.Transaction_Type> GetAllTransactionTypes() {
            return base.Channel.GetAllTransactionTypes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Transaction_Type>> GetAllTransactionTypesAsync() {
            return base.Channel.GetAllTransactionTypesAsync();
        }
        
        public void Add_Bank(UI.DataService.Bank bank) {
            base.Channel.Add_Bank(bank);
        }
        
        public System.Threading.Tasks.Task Add_BankAsync(UI.DataService.Bank bank) {
            return base.Channel.Add_BankAsync(bank);
        }
        
        public void Remove_Bank(int id) {
            base.Channel.Remove_Bank(id);
        }
        
        public System.Threading.Tasks.Task Remove_BankAsync(int id) {
            return base.Channel.Remove_BankAsync(id);
        }
        
        public void Update_Bank(UI.DataService.Bank bank) {
            base.Channel.Update_Bank(bank);
        }
        
        public System.Threading.Tasks.Task Update_BankAsync(UI.DataService.Bank bank) {
            return base.Channel.Update_BankAsync(bank);
        }
        
        public void Add_Account(UI.DataService.Account account) {
            base.Channel.Add_Account(account);
        }
        
        public System.Threading.Tasks.Task Add_AccountAsync(UI.DataService.Account account) {
            return base.Channel.Add_AccountAsync(account);
        }
        
        public void Remove_Account(int id) {
            base.Channel.Remove_Account(id);
        }
        
        public System.Threading.Tasks.Task Remove_AccountAsync(int id) {
            return base.Channel.Remove_AccountAsync(id);
        }
        
        public void Update_Account(UI.DataService.Account account) {
            base.Channel.Update_Account(account);
        }
        
        public System.Threading.Tasks.Task Update_AccountAsync(UI.DataService.Account account) {
            return base.Channel.Update_AccountAsync(account);
        }
        
        public void Add_Account_Type(UI.DataService.Account_Type accountType) {
            base.Channel.Add_Account_Type(accountType);
        }
        
        public System.Threading.Tasks.Task Add_Account_TypeAsync(UI.DataService.Account_Type accountType) {
            return base.Channel.Add_Account_TypeAsync(accountType);
        }
        
        public void Remove_Account_Type(int number) {
            base.Channel.Remove_Account_Type(number);
        }
        
        public System.Threading.Tasks.Task Remove_Account_TypeAsync(int number) {
            return base.Channel.Remove_Account_TypeAsync(number);
        }
        
        public void Update_Account_Type(UI.DataService.Account_Type accountType) {
            base.Channel.Update_Account_Type(accountType);
        }
        
        public System.Threading.Tasks.Task Update_Account_TypeAsync(UI.DataService.Account_Type accountType) {
            return base.Channel.Update_Account_TypeAsync(accountType);
        }
        
        public void Add_Customer(UI.DataService.Customer customer) {
            base.Channel.Add_Customer(customer);
        }
        
        public System.Threading.Tasks.Task Add_CustomerAsync(UI.DataService.Customer customer) {
            return base.Channel.Add_CustomerAsync(customer);
        }
        
        public void Remove_Customer(int id) {
            base.Channel.Remove_Customer(id);
        }
        
        public System.Threading.Tasks.Task Remove_CustomerAsync(int id) {
            return base.Channel.Remove_CustomerAsync(id);
        }
        
        public void Update_Customer(UI.DataService.Customer customer) {
            base.Channel.Update_Customer(customer);
        }
        
        public System.Threading.Tasks.Task Update_CustomerAsync(UI.DataService.Customer customer) {
            return base.Channel.Update_CustomerAsync(customer);
        }
        
        public void Add_Employee(UI.DataService.Employee employee) {
            base.Channel.Add_Employee(employee);
        }
        
        public System.Threading.Tasks.Task Add_EmployeeAsync(UI.DataService.Employee employee) {
            return base.Channel.Add_EmployeeAsync(employee);
        }
        
        public void Remove_Employee(int id) {
            base.Channel.Remove_Employee(id);
        }
        
        public System.Threading.Tasks.Task Remove_EmployeeAsync(int id) {
            return base.Channel.Remove_EmployeeAsync(id);
        }
        
        public void Update_Employee(UI.DataService.Employee employee) {
            base.Channel.Update_Employee(employee);
        }
        
        public System.Threading.Tasks.Task Update_EmployeeAsync(UI.DataService.Employee employee) {
            return base.Channel.Update_EmployeeAsync(employee);
        }
        
        public void Add_Transaction(UI.DataService.Transaction transaction) {
            base.Channel.Add_Transaction(transaction);
        }
        
        public System.Threading.Tasks.Task Add_TransactionAsync(UI.DataService.Transaction transaction) {
            return base.Channel.Add_TransactionAsync(transaction);
        }
        
        public void Remove_Transaction(int id) {
            base.Channel.Remove_Transaction(id);
        }
        
        public System.Threading.Tasks.Task Remove_TransactionAsync(int id) {
            return base.Channel.Remove_TransactionAsync(id);
        }
        
        public void Update_Transaction(UI.DataService.Transaction transaction) {
            base.Channel.Update_Transaction(transaction);
        }
        
        public System.Threading.Tasks.Task Update_TransactionAsync(UI.DataService.Transaction transaction) {
            return base.Channel.Update_TransactionAsync(transaction);
        }
        
        public void Add_Transaction_Type(UI.DataService.Transaction_Type transactionType) {
            base.Channel.Add_Transaction_Type(transactionType);
        }
        
        public System.Threading.Tasks.Task Add_Transaction_TypeAsync(UI.DataService.Transaction_Type transactionType) {
            return base.Channel.Add_Transaction_TypeAsync(transactionType);
        }
        
        public void Remove_Transaction_Type(int number) {
            base.Channel.Remove_Transaction_Type(number);
        }
        
        public System.Threading.Tasks.Task Remove_Transaction_TypeAsync(int number) {
            return base.Channel.Remove_Transaction_TypeAsync(number);
        }
        
        public void Update_Transaction_Type(UI.DataService.Transaction_Type transactionType) {
            base.Channel.Update_Transaction_Type(transactionType);
        }
        
        public System.Threading.Tasks.Task Update_Transaction_TypeAsync(UI.DataService.Transaction_Type transactionType) {
            return base.Channel.Update_Transaction_TypeAsync(transactionType);
        }
        
        public System.Collections.Generic.List<UI.DataService.Customer> GetCustomersofBank(int id) {
            return base.Channel.GetCustomersofBank(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Customer>> GetCustomersofBankAsync(int id) {
            return base.Channel.GetCustomersofBankAsync(id);
        }
        
        public System.Collections.Generic.List<UI.DataService.Employee> GetEmployeesofBank(int id) {
            return base.Channel.GetEmployeesofBank(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Employee>> GetEmployeesofBankAsync(int id) {
            return base.Channel.GetEmployeesofBankAsync(id);
        }
        
        public System.Collections.Generic.List<UI.DataService.Account> GetAccountsofCustomer(int id) {
            return base.Channel.GetAccountsofCustomer(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Account>> GetAccountsofCustomerAsync(int id) {
            return base.Channel.GetAccountsofCustomerAsync(id);
        }
        
        public System.Collections.Generic.List<UI.DataService.Transaction> GetTransactionsofCustomer(int id) {
            return base.Channel.GetTransactionsofCustomer(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UI.DataService.Transaction>> GetTransactionsofCustomerAsync(int id) {
            return base.Channel.GetTransactionsofCustomerAsync(id);
        }
        
        public void MakeTransaction(UI.DataService.Transaction transaction) {
            base.Channel.MakeTransaction(transaction);
        }
        
        public System.Threading.Tasks.Task MakeTransactionAsync(UI.DataService.Transaction transaction) {
            return base.Channel.MakeTransactionAsync(transaction);
        }
        
        public void MakeSome() {
            base.Channel.MakeSome();
        }
        
        public System.Threading.Tasks.Task MakeSomeAsync() {
            return base.Channel.MakeSomeAsync();
        }
    }
}
